# Generated by Django 4.2.13 on 2024-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_iframevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adsitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ad_url', models.URLField()),
            ],
        ),
    ]
