# Generated by Django 4.2.13 on 2024-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_adsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsitem',
            name='ref_url',
            field=models.URLField(default='https://default-url.com'),
        ),
    ]
